[package]
name = "revm-stub"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
stub_api.workspace = true
sync.workspace = true

[lints]
workspace = true
