[package]
name = "revm-stub"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[build-dependencies]
font-converter.workspace = true

[dependencies]
elf.workspace = true

limine.workspace = true
uefi.workspace = true

font.workspace = true
stub_api.workspace = true
sync.workspace = true

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64.workspace = true
x86_common.workspace = true

[lints]
workspace = true
